Dergipark\WorkflowBundle\Entity\DialogPost:
  type: entity
  table: bc_wf_dialog_post
  repositoryClass: Dergipark\WorkflowBundle\Entity\DialogPostRepository
  type: entity
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    sendedAt:
      column: 'sended_at'
      type: datetime
      nullable: false
    type:
      type: integer
      nullable: false
      options:
        default: 1
    text:
      type: text
      nullable: true
    fileOriginalName:
      type: string
      nullable: true
    fileName:
      type: string
      nullable: true
    reviewFormResponseContent:
      type: text
      nullable: true
  manyToOne:
    dialog:
      targetEntity: Dergipark\WorkflowBundle\Entity\StepDialog
      joinColumn:
        name: dialog_id
        referencedColumnName: id
    relatedPost:
      targetEntity: Dergipark\WorkflowBundle\Entity\DialogPost
      joinColumn:
        nullable: true
        name: related_post_id
        referencedColumnName: id
    reviewForm:
      targetEntity: Dergipark\WorkflowBundle\Entity\StepReviewForm
      joinColumn:
        name: review_form_id
        referencedColumnName: id
        nullable: true
    sendedBy:
      targetEntity: Ojs\UserBundle\Entity\User
      joinColumn:
        name: user_id
        referencedColumnName: id
  lifecycleCallbacks: {}
