Ojs\WorkflowBundle\Entity\StepReviewForm:
  type: entity
  table: bc_article_step_review_form
  repositoryClass: Ojs\WorkflowBundle\Entity\StepReviewFormRepository
  type: entity
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
    content:
      type: text
    updatedAt:
      type: datetime
      nullable: true
  manyToOne:
    step:
      targetEntity: Ojs\WorkflowBundle\Entity\ArticleWorkflowStep
      joinColumn:
        name: article_workflow_step_id
        referencedColumnName: id
  lifecycleCallbacks: {}
