Dergipark\WorkflowBundle\Entity\WorkflowStep:
  type: entity
  table: bc_wf_step
  type: entity
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    order:
      column: 'step_order'
      type: integer
      nullable: true
  lifecycleCallbacks: {}
