Ojs\JournalBundle\Entity\Article:
  preDelete:
    - { entityName: 'OjsAnalyticsBundle:ArticleStatistic', field: 'article' }
  checkUse:
    - { entityName: 'DergiparkWorkflowBundle:ArticleWorkflow', field: 'article' }