dergipark_workflow:
    resource: "routing/workflow.yml"
    prefix:   /journal/{journalId}/workflow/

dergipark_workflow_step:
    resource: "routing/wf_setting.yml"
    prefix:   /journal/{journalId}/workflow-setting/
