dergipark_workflow:
    resource: "routing/workflow.yml"
    prefix:   /journal/{journalId}/workflow/

dergipark_workflow_review_form:
    resource: "routing/journal_review_form.yml"
    prefix:   /journal/{journalId}/workflow/{stepId}/review-form

dergipark_workflow_step:
    resource: "routing/wf_setting.yml"
    prefix:   /journal/{journalId}/workflow-setting/

dergipark_workflow_article_workflow:
    resource: "routing/article_workflow.yml"
    prefix:   /journal/{journalId}/article-workflow/

dergipark_workflow_restart:
    resource: "routing/restart_workflow.yml"
    prefix:   /journal/{journalId}/restart-workflow

dergipark_workflow_article:
    resource: "routing/article.yml"
    prefix:   /journal/{journalId}/article

dergipark_workflow_users:
    resource: "routing/users.yml"
    prefix:   /journal/{journalId}/workflow/{workflowId}/users
