services:
  dergipark.workflow_extension:
    class: Dergipark\WorkflowBundle\Service\Twig\DPWorkflowTwigExtension
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@router"
      - "@translator"
      - "@ojs.journal_service"
      - "@security.token_storage"
      - "@session"
      - "@request_stack"
      - "@event_dispatcher"
      - "@dp.workflow_permission_service"
    tags:
      - { name: twig.extension }

  dp.workflow.left_menu_listener:
    class: Dergipark\WorkflowBundle\EventListener\LeftMenuListener
    arguments:
      - "@security.authorization_checker"
      - "@ojs.journal_service"
      - "@dp.workflow_permission_service"
    tags:
      - { name: kernel.event_subscriber }

  dp.workflow_service:
    class: Dergipark\WorkflowBundle\Service\WorkflowService
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@ojs.journal_service"
      - "@security.token_storage"
      - "@dp.wf_logger_service"
      - "@twig"

  dp.workflow_permission_service:
    class: Dergipark\WorkflowBundle\Service\WorkflowPermissionService
    arguments:
      - "@dp.workflow_service"

  dp.wf_logger_service:
    class: Dergipark\WorkflowBundle\Service\WorkflowLoggerService
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@ojs.journal_service"

  dp.workflow.article_submit_event_listener:
    class: Dergipark\WorkflowBundle\EventListener\ArticleSubmitEventListener
    arguments: ["@dp.workflow_service"]
    tags:
      - { name: kernel.event_subscriber }