language: php

env:
  - SYMFONY_VERSION="2.8.*" DB="postgres" SYMFONY_ENV="test"

php:
  - 7.0

addons:
  apt_packages:
    - parallel

services:
  - mysql
  - postgresql
  - elasticsearch
  - memcached

sudo: false

before_install:
  - npm install -g bower
