dp_workflow_dialog_posts_browse_review_forms:
  path:     /
  defaults: { _controller: "DergiparkWorkflowBundle:ArticleReviewForm:reviewForms" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true

dp_workflow_dialog_posts_show_review_form:
  path:     /show/{id}
  defaults: { _controller: "DergiparkWorkflowBundle:ArticleReviewForm:showForm" }
  options:
      expose: true

dp_workflow_dialog_posts_new_review_form:
  path:     /new-review-form
  defaults: { _controller: "DergiparkWorkflowBundle:ArticleReviewForm:postReviewForm" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true
