dergipark_workflow_article_workflow:
  path:     /{workflowId}
  defaults: { _controller: "DergiparkWorkflowBundle:ArticleWorkflow:timeline" }

dergipark_workflow_timeline_step:
  path:     /{workflowId}/step/{stepOrder}
  defaults: { _controller: "DergiparkWorkflowBundle:ArticleWorkflow:step" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true

dergipark_workflow_history_log:
  path:     /{workflowId}/history/log
  defaults: { _controller: "DergiparkWorkflowBundle:ArticleWorkflow:historyLog" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true

dergipark_workflow_permission_table:
  path:     /{workflowId}/permission/table
  defaults: { _controller: "DergiparkWorkflowBundle:ArticleWorkflow:permissionTable" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true

dergipark_workflow_article_detail:
  path:     /{workflowId}/article/detail
  defaults: { _controller: "DergiparkWorkflowBundle:ArticleWorkflow:articleDetail" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true

# step dialog related routing
dergipark_workflow_dialog:
    resource: "dialog.yml"
    prefix:   /{workflowId}/step/{stepOrder}

# dialog post related routing
dergipark_workflow_dialog_post:
    resource: "post.yml"
    prefix:   /{workflowId}/step/{stepOrder}/dialog/{dialogId}
