dergipark_workflow_article_workflow:
  path:     /{workflowId}
  defaults: { _controller: "DergiparkWorkflowBundle:ArticleWorkflow:timeline" }

dergipark_workflow_timeline_step:
  path:     /{workflowId}/step/{stepOrder}
  defaults: { _controller: "DergiparkWorkflowBundle:ArticleWorkflow:step" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true

dergipark_workflow_history_log:
  path:     /{workflowId}/history/log
  defaults: { _controller: "DergiparkWorkflowBundle:ArticleWorkflow:historyLog" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true

# step dialog related routing
dergipark_workflow_dialog:
    resource: "dialog.yml"
    prefix:   /{workflowId}/dialog/{stepOrder}
