dp_workflow_dialog_posts:
  path:     /posts
  defaults: { _controller: "DergiparkWorkflowBundle:DialogPost:getPosts" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true

dp_workflow_dialog_posts_new_comment:
  path:     /new-comment
  defaults: { _controller: "DergiparkWorkflowBundle:DialogPost:postComment" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true

dp_workflow_dialog_posts_browse_files:
  path:     /browse-files
  defaults: { _controller: "DergiparkWorkflowBundle:DialogPost:browseFiles" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true

dp_workflow_dialog_posts_new_file:
  path:     /new-file
  defaults: { _controller: "DergiparkWorkflowBundle:DialogPost:postFile" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true

dp_workflow_dialog_posts_browse_review_forms:
  path:     /review-files
  defaults: { _controller: "DergiparkWorkflowBundle:DialogPost:reviewForms" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true
