dp_workflow_dialog_posts:
  path:     /posts
  defaults: { _controller: "DergiparkWorkflowBundle:DialogPost:getPosts" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true

dp_workflow_dialog_posts_new_comment:
  path:     /new-comment
  defaults: { _controller: "DergiparkWorkflowBundle:DialogPost:postComment" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true
