dp_workflow_review_form:
    path:     /
    defaults: { _controller: "DergiparkWorkflowBundle:ReviewForm:index" }

dp_workflow_review_form_show:
    path:     /{id}/show
    defaults: { _controller: "DergiparkWorkflowBundle:ReviewForm:show" }

dp_workflow_review_form_new:
    path:     /new
    defaults: { _controller: "DergiparkWorkflowBundle:ReviewForm:new" }

dp_workflow_review_form_create:
    path:     /create
    defaults: { _controller: "DergiparkWorkflowBundle:ReviewForm:create" }
    methods: [POST]

dp_workflow_review_form_edit:
    path:     /{id}/edit
    defaults: { _controller: "DergiparkWorkflowBundle:ReviewForm:edit" }

dp_workflow_review_form_update:
    path:     /{id}/update
    defaults: { _controller: "DergiparkWorkflowBundle:ReviewForm:update" }
    methods:  [PUT]

dp_workflow_review_form_delete:
    path:     /{id}/delete
    defaults: { _controller: "DergiparkWorkflowBundle:ReviewForm:delete" }
    methods:  [DELETE]
