ojs_workflow_reviewers_browse:
  path:     /browse-reviewers
  defaults: { _controller: "OjsWorkflowBundle:Users:browseReviewers" }
  options:
      expose: true

ojs_workflow_section_editors_browse:
  path:     /browse-section-editors
  defaults: { _controller: "OjsWorkflowBundle:Users:browseSectionEditors" }
  options:
      expose: true

ojs_workflow_create_reviewer_user:
  path:     /create-reviewer-user
  defaults: { _controller: "OjsWorkflowBundle:Users:createReviewerUser" }
  options:
      expose: true
