ojs_workflow_step_index:
  path:     /
  defaults: { _controller: "OjsWorkflowBundle:WorkflowSetting:index" }

ojs_workflow_basic_settings:
  path:     /basic-setting
  defaults: { _controller: "OjsWorkflowBundle:WorkflowSetting:basicSetting" }
  condition: "request.isXmlHttpRequest()"

ojs_workflow_step_users_setup:
  path:     /step-users-setup/{stepOrder}
  defaults: { _controller: "OjsWorkflowBundle:WorkflowSetting:stepUsersSetup" }
  condition: "request.isXmlHttpRequest()"
  options:
      expose: true
