ojs_workflow_flow_active:
  path:     /active
  defaults: { _controller: "OjsWorkflowBundle:Workflow:actives" }
  options:
    expose: true

ojs_workflow_flow_history:
  path:     /history
  defaults: { _controller: "OjsWorkflowBundle:Workflow:history" }
